cabal-version:      3.0
name:               {{.dirname}}
version:            0.1.0.0
-- synopsis:
-- description:
license:            GPL-3.0-only
license-file:       LICENSE
-- copyright:
category:           AoC
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- extra-source-files:

common warnings
    ghc-options: -Wall

executable content
    import:           warnings
    main-is:          Main.hs
    -- other-modules:
    -- other-extensions:
    build-depends:
      , base ^>=4.20.0.0
      , extra ^>= 1.8
      , containers ^>= 0.7
      , unordered-containers ^>= 0.2.20
      , heap ^>= 1.0.4
      , split ^>= 0.2.5
      , mtl ^>= 2.3.1
      , transformers ^>= 0.6.1
      , hashable ^>= 1.4.3
      -- , regex-base ^>= 0.94
      -- , regex-pcre ^>= 0.95
      -- , raw-strings-qq ^>= 1.1
    hs-source-dirs:   app
    default-language: GHC2024
